# Generated by Django 5.0.4 on 2024-04-05 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecowatch_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastesite',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecowatch_app.video'),
        ),
    ]
