# Generated by Django 5.0.4 on 2024-04-05 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecowatch_app', '0002_wastesite_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastesite',
            old_name='name',
            new_name='city_name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
    ]
